const themes = [
  { name: "Pyro", colour: "#ef7938", path: "./assets/elements/pyro.svg" },
  { name: "Cryo", colour: "#9fd6e3", path: "./assets/elements/cryo.svg" },
  { name: "Anemo", colour: "#74c2a8", path: "./assets/elements/anemo.svg" },
  { name: "Dendro", colour: "#a5c83b", path: "./assets/elements/dendro.svg" },
  { name: "Hydro", colour: "#4cc2f1", path: "./assets/elements/hydro.svg" },
  { name: "Geo", colour: "#fab632", path: "./assets/elements/geo.svg" },
  { name: "Electro", colour: "#af8ec1", path: "./assets/elements/electro.svg" },
];

const icons = [
  { name: "Albedo", path: "./assets/icons/albedo_icon.webp", theme_id: 6 },
  {
    name: "Alhaitham",
    path: "./assets/icons/alhaitham_icon.webp",
    theme_id: 4,
  },
  {
    name: "Arataki",
    path: "./assets/icons/arataki_Itto_icon.webp",
    theme_id: 6,
  },
  { name: "Baizhu", path: "./assets/icons/baizhu_icon.webp", theme_id: 4 },
  { name: "Chiori", path: "./assets/icons/chiori_icon.webp", theme_id: 6 },
  { name: "Cyno", path: "./assets/icons/cyno_icon.webp", theme_id: 7 },
  { name: "Dehya", path: "./assets/icons/dehya_icon.webp", theme_id: 1 },
  { name: "Diluc", path: "./assets/icons/diluc_icon.webp", theme_id: 1 },
  { name: "Eula", path: "./assets/icons/eula_icon.webp", theme_id: 2 },
  { name: "Furina", path: "./assets/icons/furina_icon.webp", theme_id: 5 },
  { name: "Ganyu", path: "./assets/icons/ganyu_icon.webp", theme_id: 2 },
  { name: "Hu tao", path: "./assets/icons/hu_tao_icon.webp", theme_id: 1 },
  { name: "Jean", path: "./assets/icons/jean_icon.webp", theme_id: 3 },
  {
    name: "Kaedehara Kazuha",
    path: "./assets/icons/kaedehara_kazuha_icon.webp",
    theme_id: 3,
  },
  {
    name: "Kamisato Ayaka",
    path: "./assets/icons/kamisato_ayaka_icon.webp",
    theme_id: 2,
  },
  {
    name: "Kamisato Ayato",
    path: "./assets/icons/kamisato_ayato_icon.webp",
    theme_id: 5,
  },
  { name: "Keqing", path: "./assets/icons/keqing_icon.webp", theme_id: 7 },
  { name: "Klee", path: "./assets/icons/klee_icon.webp", theme_id: 1 },
  { name: "Lyney", path: "./assets/icons/lyney_icon.webp", theme_id: 1 },
  { name: "Mona", path: "./assets/icons/mona_icon.webp", theme_id: 5 },
  { name: "Nahida", path: "./assets/icons/nahida_icon.webp", theme_id: 4 },
  { name: "Navia", path: "./assets/icons/navia_icon.webp", theme_id: 6 },
  {
    name: "Neuvillette",
    path: "./assets/icons/neuvillette_icon.webp",
    theme_id: 5,
  },
  { name: "Nilou", path: "./assets/icons/nilou_icon.webp", theme_id: 5 },
  { name: "Qiqi", path: "./assets/icons/qiqi_icon.webp", theme_id: 2 },
  {
    name: "Raiden Shogun",
    path: "./assets/icons/raiden_shogun_icon.webp",
    theme_id: 7,
  },
  {
    name: "Sangonomiya Kokomi",
    path: "./assets/icons/sangonomiya_kokomi_icon.webp",
    theme_id: 5,
  },
  { name: "Shenhe", path: "./assets/icons/shenhe_icon.webp", theme_id: 2 },
  {
    name: "Tartaglia",
    path: "./assets/icons/tartaglia_icon.webp",
    theme_id: 5,
  },
  { name: "Tighnari", path: "./assets/icons/tighnari_icon.webp", theme_id: 4 },
  { name: "Venti", path: "./assets/icons/venti_icon.webp", theme_id: 3 },
  { name: "Wanderer", path: "./assets/icons/wanderer_icon.webp", theme_id: 3 },
  {
    name: "Wriothesley",
    path: "./assets/icons/wriothesley_icon.webp",
    theme_id: 2,
  },
  { name: "Xianyun", path: "./assets/icons/xianyun_icon.webp", theme_id: 3 },
  { name: "Xiao", path: "./assets/icons/xiao_icon.webp", theme_id: 3 },
  { name: "Yae Miko", path: "./assets/icons/yae_miko_icon.webp", theme_id: 7 },
  { name: "Yelan", path: "./assets/icons/yelan_icon.webp", theme_id: 5 },
  { name: "Yoimiya", path: "./assets/icons/yoimiya_icon.webp", theme_id: 1 },
  { name: "Zhongli", path: "./assets/icons/zhongli_icon.webp", theme_id: 6 },
];

export { themes, icons };
